MODEL:
  NUM_CLASSES: 2
  PRIORS:
    FEATURE_MAPS: [40, 20, 10, 5, 3, 1]
    STRIDES: [8, 16, 32, 64, 107, 320]
    MIN_SIZES: [15, 45, 75, 105, 135, 165]
    MAX_SIZES: [45, 75, 105, 135, 165, 195]
    ASPECT_RATIOS: [[0.5, 1, 1.5], [0.5, 1, 1.5], [0.5, 1, 1.5], [0.5, 1, 1.5], [0.5, 1, 1.5], [0.5, 1, 1.5]]
    BOXES_PER_LOCATION: [8, 8, 8, 8, 8, 8]
INPUT:
  IMAGE_SIZE: 320
  PIXEL_MEAN: [170, 109, 159]
DATASETS:
  TRAIN: ("/content/kidney_dataset_320_6/train", )
  TEST: ("/content/kidney_dataset_320_6/test", )
SOLVER:
  MAX_ITER: 10000
  LR_STEPS: [3000, 6000]
  GAMMA: 0.1
  BATCH_SIZE: 16
  LR: 1e-3

OUTPUT_DIR: '/content/drive/MyDrive/HuBMAP/dssd_torch'